### ISSUE TITLE
Questions about this project

### ISSUE THREAD

**Issue by sudomain** [brenthuisman/par2deep#20]
Hello,

I read the README and some of the existing issues and have some questions:

1.) This project doesn't use par2cmdline correct?

2.) How does it handle renaming of files? If a `testfile` is renamed to `testfile2`, but the file content doesn't change, then new recovery blocks aren't needed. Does par2deep account for this?

3.) What's the default behavior when a file is updated and par2deep is run again? Are the old par files overwritten by the new ones?

**Comment by brenthuisman** [comment]
Hi @sudomain,

Thanks for your interest!

1. It does not require a build of `par2cmdline`, although it can be used with it. `par2deep` does use a copy of `par2cmdline` internally, see my `libpar2` repo.
2. It does not.
3. par2 can only detect change, not whether or not those changes are intentional. If you run `par2deep`, you'll see you get the option of restoring the file (if enough parity data is available) or recreating the parity data.
