### ISSUE TITLE
AttributeError: 'par2deep' object has no attribute 'unused' 

### ISSUE THREAD

**Issue by cameo69** [brenthuisman/par2deep#21]
I am getting below error on Mac OS.
Version is v1.9.4 and installed via pip.

```
/Users/myuser/Library/Python/3.9/bin/par2deep-cli -pcmd /usr/local/bin/par2 -keepor

Using /usr/local/bin/par2 ...
Looking for files in /Users/myuser/Downloads/Tanz2018/Tanz2018_library_01_copy.fcpbundle ...
==========================================================
Will create 4317 new par2 files.
Display these files?  [Y/n] 
n
Will replace 0 par2 files because parity data is incomplete (missing file).
Will verify 0 par2 files.
Traceback (most recent call last):
  File "/Users/myuser/Library/Python/3.9/bin/par2deep-cli", line 8, in <module>
    sys.exit(main())
  File "/Users/myuser/Library/Python/3.9/lib/python/site-packages/par2deep/cli.py", line 48, in main
    print('Will remove',len(p2d.unused),'unused par2 files.')
AttributeError: 'par2deep' object has no attribute 'unused'  
```

Any hint how to fix this is appreciated?

**Comment by brenthuisman** [comment]
Just after the 1.9.4 release this bug was found and fixed, see https://github.com/brenthuisman/par2deep/commit/42d94ec741a75a434e8344db26fc0a2961929461#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

At the time I assumed some more releases with this update would follow, but that never really happened. When I have time for working on `par2deep`, I'll retry a port to `gopar`, as it should fix a bunch of open Issues, but that won't happen soon (maybe over the holidays).

In the meantime, you could grab an earlier version off of PyPI. Let me know if that works!

**Comment by mymy-dot** [comment]
Would be nice if you could just merge that fix. Shouldn't take much effort, no?  (without any of the other changes) I mean I'll work around it, I managed to find this thread, just would have saved me a couple of minutes if you fixed it.

**Comment by brenthuisman** [comment]
It is merged already, that's the commit I pointed you at.
